name: 1vs1
main: Minifixio\onevsone\OneVsOne
version: 0.0.5
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
description: 1vs1 Plugin
permissions:
  onevsone.refarena:
    description: "Allows using /refarena"
    default: op
