name: StatsPVP
main: Minifixio\statspvp\StatsPVP
version: 0.0.1
api: [1.0.0, 1.1.0]
description: Stats pour PVP
permissions:
    statspvp.stats:
        default: op
        description: Affiche les statistiques du joueur